name: 'Terraform Manual Execution'

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose an action'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy
      bastion_state:
        description: 'Bastion Host State (Only used if action is apply)'
        required: true
        default: 'running'
        type: choice
        options:
          - running
          - stopped

env:
  AWS_REGION: 'ap-south-1'
  TF_VERSION: '1.5.0'

jobs:
  terraform:
    name: 'Terraform Execution'
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        if: github.event.inputs.action == 'apply'
        id: plan
        # Pass the bastion_state variable into the plan
        run: terraform plan -var="bastion_state=${{ github.event.inputs.bastion_state }}" -out=tfplan

      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        run: terraform apply -auto-approve tfplan

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve
